name: infra_pipeline
on:
  workflow_dispatch:
    inputs:
      environment:
        description: select env
        required: true
        type: choice
        options:
          - dev
          - prod
jobs:
  hello:
    runs-on: self-hosted
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name : install terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false
          terraform_version: latest

      - name: create tfvars
        working-directory: env/dev
        env:
          tfvars-content: ${{ secrets.TF_VARS }}
        run: |
          echo "tfvars-content" >> terraform.tfvars