name: infra_test
on:
  push:
  # workflow_dispatch:
    # inputs:
    #   environment:
    #     description: select env
    #     required: true
    #     default: dev
    #     type: choice
    #     options:
    #       - dev
    #       - prod
jobs:
  infra_terraform:
    runs-on: self-hosted
    steps:
      - name: checkout code
        uses: actions/checkout@v4 

      - name: install terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: version terraform
        run: terraform version

      - name: TFVARS terraform
        working-directory: env/dev
        env:
          TFVARS_CONTENT: ${{ secrets.TF_VARS }}
        run: |
          echo "$TFVARS_CONTENT" > terraform.tfvars
      
      - name: terraform init
        working-directory: env/dev
        run: terraform init

      - name: terraform plan
        working-directory: env/dev
        run: terraform plan -var-file="terraform.tfvars"
      
      
